const highlightColor = '#ff0000ff';
const keyboardShortcutStyle = {
    color:"#ffee00ff",
    textShadow:' -1px -1px 0 '+highlightColor+', 1px -1px 0 '+highlightColor+', -1px 1px 0 '+highlightColor+', 1px 1px 0 '+highlightColor,
}


export  const ascii_rose = <div className = "ascii_graphics" style = {{fontSize:'6px',margin:'auto',paddingTop:'20px'}}>{` ._-\\                           +....                                                 
 \\   \\\\                          .   \\.                         __,^._________________
/_| \\=  .                        \\.   )                       ,............ ....._=-^ 
+{ #.  =..\\_                      .    .                ,.......          |/          
/_#^ /  \\........_                .   : \"           ,^....                            
  _.  _-)   ---- ......_______    \\..  /         ,....                                
  /__/ /            /..........\\___\\..y _,^........\`                                  
 ^   |/          .+     .  , \\.............------/                                    
               ._     _/         ,                                                    
              ,x..._;^                                                                `}</div>
export  const ascii_rocket = <div className = "ascii_graphics" style = {{fontSize:'6px',margin:'auto',paddingTop:'20px'}}>
{`                                 /--/+---------      .    ..                          
                                |  | ........ /    \`\`\`..........                      
        ________________________/_/ .._....._/___\`_\`...\`\` \`\`\`....\`\` \`\`                
 __--^^^  \\             _______                    \\ \`\`\`\`\`\`\`\`  \`\`\`\`\`\`     \`\`\`\`\`\`\`\`\`\`  
<.........|..       ... )**====). __   __  __ - ---|  \`\`        \`              .......
 ^^--;;;../ ..... .... /**====/...\\          \\-----/         ..... ............  ..   
         \`\`^^^\`\`\`\`\`^^^^\`\`\`\`\`\`\`\`^^T^\\__________\\^^\`^ \`\` ............  ....             
                                \\--.-------       \`\`\`\`\`\`\`\`\`\`   \`\`                     
                                                     \`\`  \`\`                           
`}</div>

// export const ascii_title = <div className = "ascii_graphics" style = {{width:'500ch',color:'#0000ff',whiteSpace:'pre',fontSize:'2px',textShadow:'10px 10px #ff00ff'}}>
//           {`
//                                                        kkkkkkkkk                                                                                                        tt                                                                  hhhhhhhhhh                                             bbbbbbbbbb                                                                                                                                                           kkkkkkkkkk                                  
//                                                        kkkkkkkkk                                                                                                 tttttttttt                                                                 hhhhhhhhhh                                             bbbbbbbbbb                                                                                                                                                           kkkkkkkkkk                                  
//                                                        kkkkkkkkk                                                                                                 tttttttttt                                                                 hhhhhhhhhh                                             bbbbbbbbbb                                                                                                                                                           kkkkkkkkkk                                  
//                                                        kkkkkkkkk                                                                                                 tttttttttt                                                                 hhhhhhhhhh                                             bbbbbbbbbb                                                                                                                                                           kkkkkkkkkk                                  
//             ssssssssssssssssssssss                     kkkkkkkkk                   kkkkkkkkkkkkk                   eeeeeeeeeeeeeeeeeeeee                   tttttttttttttttttttttttt                   cccccccccccccccccccc                  hhhhhhhhhh     hhhhhhhhhhhhhhhhhhh                     bbbbbbbbbb     bbbbbbbbbbbbbbbbbb                                 ooooooooooooooooooooo                                  ooooooooooooooooooooo                       kkkkkkkkkk                   kkkkkkkkkkkk   
//       ssssssssssssssssssssssssssssssssss               kkkkkkkkk               kkkkkkkkkkkkkk                eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee            ttttttttttttttttttttttttt            ccccccccccccccccccccccccccccccccc            hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh               bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                    ooooooooooooooooooooooooooooooooooo                    ooooooooooooooooooooooooooooooooooo                kkkkkkkkkk              kkkkkkkkkkkkkk      
//     sssssssssss               sssssssssssss            kkkkkkkkk          kkkkkkkkkkkkkk                 eeeeeeeeeeeeee              eeeeeeeeeeeee              ttttttttttt                 ccccccccccccc             ccccccccccccc         hhhhhhhhhhhhhhhhh            hhhhhhhhhhhhh             bbbbbbbbbbbbbbbb             bbbbbbbbbbbbb              oooooooooooooo             oooooooooooooo              oooooooooooooo             oooooooooooooo             kkkkkkkkkk          kkkkkkkkkkkkkk          
//    ssssssssss                    ssssssssss            kkkkkkkkk     kkkkkkkkkkkkkkk                   eeeeeeeeeee                       eeeeeeeeeee             tttttttttt               ccccccccccc                     ccccccccccc       hhhhhhhhhhhh                    hhhhhhhhhhh            bbbbbbbbbbbb                     bbbbbbbbbbb         oooooooooooo                       ooooooooooo         oooooooooooo                       ooooooooooo           kkkkkkkkkk     kkkkkkkkkkkkkk               
//     sssssssssssssssssss                                kkkkkkkkkkkkkkkkkkkkkkkk                       eeeeeeeeee                           eeeeeeeeee            tttttttttt             ccccccccccc                         c               hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbbb                         bbbbbbbbbb       ooooooooooo                           oooooooooo        oooooooooo                           ooooooooooo         kkkkkkkkkkkkkkkkkkkkkkkkk                   
//       sssssssssssssssssssssssssssssss                  kkkkkkkkkkkkkkkkkkkkkkkkk                     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee            tttttttttt             cccccccccc                                          hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbb                           bbbbbbbbb       oooooooooo                             oooooooooo      oooooooooo                             oooooooooo         kkkkkkkkkkkkkkkkkkkkkkkkk                   
//             sssssssssssssssssssssssssssssss            kkkkkkkkkkkkkkkkkkkkkkkkkkkk                  eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee            tttttttttt             cccccccccc                                          hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbb                           bbbbbbbbb       oooooooooo                             oooooooooo      oooooooooo                             oooooooooo         kkkkkkkkkkkkkkk kkkkkkkkkkkk                
//                             sssssssssssssssss          kkkkkkkkkk        kkkkkkkkkkkkk                eeeeeeeeee                                                 tttttttttt             ccccccccccc                          c              hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbb                          bbbbbbbbbb       ooooooooooo                           ooooooooooo      ooooooooooo                           ooooooooooo         kkkkkkkkkk         kkkkkkkkkkkk             
//   ssssssssss                       ssssssssss          kkkkkkkkk            kkkkkkkkkkkkk             eeeeeeeeeeee                        eeeeeeeeeee            tttttttttt              ccccccccccc                       cccccccccc       hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbbbb                      bbbbbbbbbbb         ooooooooooo                         ooooooooooo        ooooooooooo                         ooooooooooo          kkkkkkkkkk            kkkkkkkkkkkk          
//    ssssssssssss                  ssssssssssss          kkkkkkkkk               kkkkkkkkkkkkk            eeeeeeeeeeeee                  eeeeeeeeeeeee             tttttttttt                cccccccccccc                 cccccccccccc        hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbbbbbbb                bbbbbbbbbbbbb            ooooooooooooo                 ooooooooooooo            ooooooooooooo                 ooooooooooooo            kkkkkkkkkk              kkkkkkkkkkkkk       
//      ssssssssssssssssssssssssssssssssssssss            kkkkkkkkk                  kkkkkkkkkkkkk            eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee                ttttttttttttttttttt         cccccccccccccccccccccccccccccccccccc           hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb                 ooooooooooooooooooooooooooooooooooooooo                ooooooooooooooooooooooooooooooooooooooo              kkkkkkkkkk                 kkkkkkkkkkkkkk   
//          ssssssssssssssssssssssssssssss                kkkkkkkkk                     kkkkkkkkkkkk              eeeeeeeeeeeeeeeeeeeeeeeeeeeeee                      ttttttttttttttttt              ccccccccccccccccccccccccccc               hhhhhhhhhh                       hhhhhhhhhh            bbbbbbbbb  bbbbbbbbbbbbbbbbbbbbbbbb                           ooooooooooooooooooooooooooooo                          ooooooooooooooooooooooooooooo                   kkkkkkkkkk                    kkkkkkkkkkkkk`}
// </div>

export const ascii_title = <div className = "ascii_graphics" style = {{width:'fit-content',color:'#0000ff',whiteSpace:'pre',fontSize:'5px',textShadow:'2px 2px #ff00ff'}}>
{`         ddd\>                                                    "tt%                  '$$$   
    ,!   ddd\>        !       \`~:                                 ttt%                  @$$$   
!ddddddddddd>  Yrrrrrrr/ kaaaaaaaaaa  www@   wwww8   wwwJ      Zttttttt  xxxx_ @xxx)  $$$$$$$ 
ddd;    :ddd>  Yrrr-            #aaa   wwwi Xwwwww  @www         ttt%      xxxxxxh     @$$$   
ddd      ddd>  Yrrr      %aaaaBq-aaa    www www www<www          ttt%      ixxxxx      @$$$   
dddd    dddd>  Yrrr     uaaa    aaaa     wwwww  ;wwwww    @@@.   tttt     xxxx^xxxx    %$$$   
  dddddd;ddd>  Yrrr      }aaaaaa-aaaz    cwww/   @www     ...z   -ttttt xxxx"   #xxxB   $$$$$x

`}</div>
export const ascii_wire = <div className = "ascii_graphics" style = {{overflow:'hidden',position:'absolute',top:'-150px',left:'0px',width:'972ch',color:'#0000ff',whiteSpace:'pre',fontSize:'2.5px'}}>
{`                                                /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                                                                               /|                               
                              |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                                                             |\\               | |                               
                              | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                                                             | |              | .                               
                              );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                                                             );|              y /                               
                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                                              |:|             | |                                
                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                                               |:|            | |                                
                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                                               ^| |           y .                                
                                |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                                                 |:|          |;|                                 
                                |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                                                  |:| _ _.--_._h;|        ______.                  
__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.__ _-------.__    __-----.____ _-| | | | | |  \\7----__-- _____;--------_  _-----.
  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----  -+________  --_-  _____.__  -_.Y | i _x   -- \\----= _-=  ##==__==____--* __----
-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______-_  -==     =-__ ---###^^^__-_  -| .\\:\\_|:|_\\ \\:\\___-=---===^   -________--______
  -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                                 -------_______-______---    ---/\\_/*- .- * +-\\:\\                               
                                .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                                                              .;/             \\ \\                              
                               /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                                                            /;/               \\ \\                             
                              / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                                                          / /                 \\_\\                            
                             / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                                                        / /                    -.                           
                            *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                                              *-^                                                  
`}
</div>
export const aboutText = (
    <div style = {{padding:'10px'}}>
    {ascii_rose}
    <div style ={{width:'fit-content',margin:'auto'}}>+---------------------------------------------------+</div>
    <div style = {{marginTop:'10px'}}>
    <span style = {{backgroundColor:'blue',color:'white'}}>
    This is a sketchbook designed for experimenting with monospace text, because it's all text anyway!! I originally wrote this page just as a simple drawing program to help me make ascii art, but it's since
    developed into a technical exploration of drawing/rendering using raw HTML text on a webpage, but also just a way of exploring the strange rulebreaking of ascii art.
    Text can be copied from this sketchbook or pasted into it from other sources, or typed directly onto the canvas like using a typewriter.
    The thing I'm working on now is a word-renderer, where images can be rendered using words to write visual poems.
    </span>
    <br></br>
    <br></br>
    <span style = {{backgroundColor:'blue',color:'white'}}>
    written by <a style = {keyboardShortcutStyle}href = "https://alexlafetra.github.io">alex lafetra</a> summer 2025
    </span>
    <br></br>
    <a style = {{marginLeft:'10px',fontStyle:'italic',color:'red'}} href = "https://github.com/alexlafetra/asciisketchbook">github</a>
    <br></br>
    <div style ={{width:'fit-content',margin:'auto'}}>{'<3'}</div>
    </div>
    <br></br>
    <div style ={{width:'fit-content',margin:'auto'}}>+---------------------------------------------------+</div>
    {ascii_rocket}
    <br></br>
    <div>
    <span style = {{backgroundColor:'blue',color:'white'}}>
    <span style = {keyboardShortcutStyle}>the basics</span><br></br>
    Typing text enters it into the canvas at the cursor location, which advances as you write. The cursor can also be moved by clicking around and the arrow keys.
    <br></br><br></br>
    Shift clicking+dragging will create a selection box, which can be filled with a character when typed or cut, copied, moved with the arrow keys, and dragged with the mouse. By default, whitespaces will be treated as "transparent" when moving or pasting text.
    </span>
    </div>
    <br></br>
    <div style ={{width:'fit-content',margin:'auto'}}>+----------------------------------------+</div>
    <span style = {{...keyboardShortcutStyle,backgroundColor:'blue'}}>tools</span><br></br>
    <div style = {{
      displaybackgroundColor:'blue',
      color:'white',
      marginLeft:"40px",
      display:'grid',
      gridTemplateColumns:'80px auto',
      gridTemplateRows:'repeat(6,auto)',
      gridTemplateAreas:`'description0 description0'
                          'title1 description1'
                          'title2 description2'
                          'title3 description3'
                          'title4 description4'
                          'title5 description5'
                          'title6 description6'`,
      width:'400px',
      gap:'10px'

      }}>
    <span style = {{gridArea:'description0',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>The character drawn is the last character pressed, shown in the top left display box.</span>
    <span style = {keyboardShortcutStyle}>Brush ...</span><span style = {{gridArea:'description1',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>draw freehand lines by dragging the mouse. Brush thickness can be changed with the slider. Tick 'dynamic' to draw lines that resize thickness based on the speed that they're drawn with.</span>
    <span style = {keyboardShortcutStyle}>Lines ...</span><span style = {{gridArea:'description2',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>draw straight lines by dragging the mouse.</span>
    <span style = {keyboardShortcutStyle}>Stamp ...</span><span style = {{gridArea:'description3',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>draw using a copied section of the canvas as a brush.</span>
    <span style = {keyboardShortcutStyle}>Fill ....</span><span style = {{gridArea:'description4',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>fill an area using the current character (like a 'bucket fill')</span>
    <span style = {keyboardShortcutStyle}>Images ..</span><span style = {{gridArea:'description5',color:'white',backgroundColor:'blue',width:'fit-content',height:'fit-content'}}>render an image to the canvas with the 'render image' button, or by pasting an image from the clipboard. You can control image contrast, brightness, and the character pallette used to render the image.At first the image is drawn to a separate layer, but can be committed to the drawing and edited like normal text.</span>
    </div>
    <div style ={{width:'fit-content',margin:'auto'}}>+----------------------------------------+</div>
    <br></br>
    <div>
    <span style = {{...keyboardShortcutStyle,backgroundColor:'blue'}}>keyboard shortcuts</span><br></br>
    </div>
        <div style = {{
      displaybackgroundColor:'blue',
      color:'white',
      marginLeft:"40px",
      display:'grid',
      gridTemplateColumns:'auto auto',
      gridTemplateRows:'repeat(13,auto)',
      gridTemplateAreas:`'description0 description0'
                          'title1 description1'
                          'title2 description2'
                          'title3 description3'
                          'title4 description4'
                          'title5 description5'
                          'title6 description6'`,
      width:'300px',
      gap:'10px'

      }}>
      <span style = {keyboardShortcutStyle}>Cmd+A .........</span><span style = {{color:'white',backgroundColor:'blue'}}>select all</span>
      <span style = {keyboardShortcutStyle}>Cmd+Shift+A ...</span><span style = {{color:'white',backgroundColor:'blue'}}>deselect all</span>
      <span style = {keyboardShortcutStyle}>Cmd+Z .........</span><span style = {{color:'white',backgroundColor:'blue'}}>undo</span>
      <span style = {keyboardShortcutStyle}>Cmd+Shift+Z ...</span><span style = {{color:'white',backgroundColor:'blue'}}>redo</span>
      <span style = {keyboardShortcutStyle}>Cmd+X .........</span><span style = {{color:'white',backgroundColor:'blue'}}>cut selected area</span>
      <span style = {keyboardShortcutStyle}>Cmd+C .........</span><span style = {{color:'white',backgroundColor:'blue'}}>copy selected area</span>
      <span style = {keyboardShortcutStyle}>Cmd+V .........</span><span style = {{color:'white',backgroundColor:'blue'}}>paste clipboard</span>
      <span style = {keyboardShortcutStyle}>Cmd+Backspace .</span><span style = {{color:'white',backgroundColor:'blue'}}>clear Canvas</span>
      <span style = {keyboardShortcutStyle}>Backspace .....</span><span style = {{color:'white',backgroundColor:'blue'}}>delete character</span>
      <span style = {keyboardShortcutStyle}>Arrow keys ....</span><span style = {{color:'white',backgroundColor:'blue'}}>move cursor or translate selected text</span>
      <span style = {keyboardShortcutStyle}>Arrow keys + <br></br>Shift .........</span><span style = {{color:'white',backgroundColor:'blue'}}>translate row/column</span>
      <span style = {keyboardShortcutStyle}>Enter .........</span><span style = {{color:'white',backgroundColor:'blue'}}>move cursor down a line</span>
      <span style = {keyboardShortcutStyle}>Enter+Shift ...</span><span style = {{color:'white',backgroundColor:'blue'}}>insert blank line</span>
    </div>
    {/* Understanding technology as a physical, human, inherently political resource--as opposed to the neutral, fingerprint-less identity most tech companies portray it as--limits our ability to conceptualize the labor, violence, and natural resources that go into producing, maintaining, and integrating ourselves with technology. */}
    <br></br>
    {/* Missile guidance systems are written with the same alphabet, the same text encoding, and stored in the same ascii format as what you create on this page. Abstracting technology from its physical reality is a strategy for depersonifying the people targeted by it, and alleviating the consequences for those who develop it. */}
    {/* <br></br> */}
    {/* {ascii_rose}                                                      */}
    </div>
  )